from GUI.AbstractScreen import AbstractScreen
from GUI.AnalysisScreen import AnalysisScreen
from GUI.CourseInfoScreen import CourseInfoScreen
from GUI.CreateCourseScreen import CreateCourseScreen
from GUI.ErrorScreen import ErrorScreen
from GUI.GUIController import GUIController
from GUI.MainScreen import MainScreen
from GUI.SelectionScreen import SelectionScreen
from GUI.TotalsScreen import TotalsScreen
