# COMMANDS
CMD_PRINT = "print"
CMD_SET = "set"
CMD_INPUT = "input"
CMD_CREATE = "create"
CMD_LIST = "list"
CMD_COMMIT = "commit"
CMD_EXIT = "exit"
CMD_TOTALS = "totals"
CMD_HELP = "help"

# MARK BOOK TABLE HEADERS
GROUP = "Group"
DESCRIPTION = "Description"
MARK = "Mark"

GOAL = "GOAL"
COURSE_NAME = "COURSE NAME"
DATA = "DATA"
WEIGHT = "WEIGHT"
CURRENT_MARK = "CURRENT MARK"

NON_DATA_VALUES = [DESCRIPTION, CURRENT_MARK, GOAL]
WEIGHTS = 'WEIGHTS'

NAME = "NAME"
ENTRIES = "ENTRIES"
